# Generated by Django 4.0.1 on 2022-01-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_post_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(limit_choices_to={'is_public'}, on_delete=django.db.models.deletion.CASCADE, to='instagram.post'),
        ),
    ]
